### ISSUE TITLE
Create web version of new benefit cards

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-api#239]

**Comment by kc-accidental** [comment]
<img width="641" alt="Screen Shot 2024-01-24 at 1 09 22 PM" src="https://github.com/Gary-Community-Ventures/benefits-api/assets/149400219/0d9c46d5-2785-4dfd-a97e-6dcb2be3ddbf">

Since you mentioned the categories and basing it off the the mobile prototypes, I took off the icon from the card.
I left another design choice of the card with the icon underneath just in case.

**Comment by sydney-devine** [comment]
> <img alt="Screen Shot 2024-01-24 at 1 09 22 PM" width="641" src="https://private-user-images.githubusercontent.com/149400219/299429930-0d9c46d5-2785-4dfd-a97e-6dcb2be3ddbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMjQwOTYsIm5iZiI6MTcwNjEyMzc5NiwicGF0aCI6Ii8xNDk0MDAyMTkvMjk5NDI5OTMwLTBkOWM0NmQ1LTI3ODUtNGRmZC1hOTdlLTZkY2IyYmUzZGRiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNFQxOTE2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZGI4ZmZhYmFlMjNiNTQyNzAxOGEzMWViMmZhNDA0MjVlNWFhZWI3YzE1YzJkOTcxOGI4ZWU0ZWE1MDU1MjI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Yfr0WU7z9lKWfHddK2uyLfYz7TKu9jSqi050sa3lGZc">
> Since you mentioned the categories and basing it off the the mobile prototypes, I took off the icon from the card. I left another design choice of the card with the icon underneath just in case.

Thank you!!
