### ISSUE TITLE
SNAP Medical Expense Deduction

### ISSUE THREAD

**Issue by Linda-Vu** [Gary-Community-Ventures/benefits-api#566]
Need this updated for pilot -

Refine SNAP rules for households with members 60+ and/or with disabilities as follows:

Send medical expenses to PE for households with a member who is 60+ and/or has disabilities. For these HHs, deduct reported medical expenses above $35. (NC SNAP Policy manual FNS 340 Deductions Sec. 340.13 "Medical Deductions")

For HHs with a member who is 60+ and/or has a disability, do not limit the excess shelter deduction amount. These HHs will get the full excess shelter deduction. (Sec. 340.12) (this rule is same for NC and CO)

Colorado is also working to update the with this same deduction but their calculation is different from NC. ticket for that here: https://github.com/Gary-Community-Ventures/benefits-api/issues/556

**Comment by Linda-Vu** [comment]
needs research from @msrezaie & @bespinosa01 about what effort we may need in policyengine to enable this. this ticket can be worked after that, and after this one is complete: https://github.com/Gary-Community-Ventures/benefits-api/issues/568

**Comment by msrezaie** [comment]
From my research and my current understanding the implementation for this in the screener codebase would be the same between the different states as the calculations are done by the policy engine. In order to make a household eligible for standard medical deductions, I believe a household's medical expenses needs to be sent to the policy engine. Currently in the screener there as an expense option called `medical` which is mapped to 'Medical insurance premium &/or bills' which is currently not utilized and can be used for sending medical expenses.
